---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: consul
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - name: consul
        image: consul:latest
        args: 
        - agent 
        - -server
        - -bootstrap-expect
        - "3"
        - -client
        - 0.0.0.0
...
---
apiVersion: v1
kind: Service
metadata:
  name: consul
spec:
  selector:
    app: consul
  ports:
  - name: http
    port: 8500
  - name: dns
    port: 8600
...
---
apiVersion: v1
kind: Service
metadata:
  name: consul-cluster
spec:
  selector:
    app: consul
  ports:
  - name: lan
    port: 8301