---
apiVersion: v1
kind: ConfigMap
metadata:
  name: consul
data:
...
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: consul
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - name: consul
        image: consul:latest
        args: 
        - agent 
        - -server
        - -bootstrap-expect
        - "3"
        - -advertise
        - consul
...
---
apiVersion: v1
kind: Service
metadata:
  name: consul
spec:
  ports:
  - name: http
    port: 8500
  - name: dns
    port: 8600