apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vault
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vault
    spec:
      volumes:
      - name: vault-config
        configMap:
          name: vault
      containers: 
      - name: consul-agent
        image: consul:latest
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        args:
        - agent
        - -data-dir=/consul/data
        - -retry-join=consul-0.consul.$(NAMESPACE).svc.cluster.local
        - -retry-join=consul-1.consul.$(NAMESPACE).svc.cluster.local
        - -retry-join=consul-2.consul.$(NAMESPACE).svc.cluster.local
        lifecycle:
          preStop:
            exec:
              command:
              - consul
              - leave

      - name: vault
        image: vault:latest
        securityContext:
          capabilities:
            add: 
            - IPC_LOCK
        volumeMounts:
        - name: vault-config
          mountPath: /vault/config