apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vault
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: vault:latest
        capabilities:
        - IPC_LOCK
...
---
apiVersion: v1
kind: Service
metadata:
  name: vault
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8200